import { StarEmptyIcon, StarFillIcon, StarHalfIcon } from 'components/icons';
import styled from 'styled-components';

interface Props {
  rating: number;
  size?: string;
}

export const Rating = ({ rating, size = '14px' }: Props) => {
  return (
    <Div>
      {
        (rating == 1)
        &&
        <>
          <StarFillIcon 
            width={size}
            height={size}
            color="#F9D71C"
          />
          <StarEmptyIcon 
            width={size}
            height={size}
            color="#F9D71C"
          />
          <StarEmptyIcon 
            width={size}
            height={size}
            color="#F9D71C"
          />
          <StarEmptyIcon 
            width={size}
            height={size}
            color="#F9D71C"
          />
          <StarEmptyIcon 
            width={size}
            height={size}
            color="#F9D71C"
          />
        </>
      }
      {
        (rating < 2 && rating > 1)
        &&
        <>
          <StarFillIcon 
            width={size}
            height={size}
            color="#F9D71C"
          />
          <StarHalfIcon 
            width={size}
            height={size}
            color="#F9D71C"
          />
          <StarEmptyIcon 
            width={size}
            height={size}
            color="#F9D71C"
          />
          <StarEmptyIcon 
            width={size}
            height={size}
            color="#F9D71C"
          />
          <StarEmptyIcon 
            width={size}
            height={size}
            color="#F9D71C"
          />
        </>
      }
      {
        (rating == 2)
        &&
        <>
          <StarFillIcon 
            width={size}
            height={size}
            color="#F9D71C"
          />
          <StarFillIcon 
            width={size}
            height={size}
            color="#F9D71C"
          />
          <StarEmptyIcon 
            width={size}
            height={size}
            color="#F9D71C"
          />
          <StarEmptyIcon 
            width={size}
            height={size}
            color="#F9D71C"
          />
          <StarEmptyIcon 
            width={size}
            height={size}
            color="#F9D71C"
          />
        </>
      }
      {
        (rating < 3 && rating > 2)
        &&
        <>
          <StarFillIcon 
            width={size}
            height={size}
            color="#F9D71C"
          />
          <StarFillIcon 
            width={size}
            height={size}
            color="#F9D71C"
          />
          <StarHalfIcon 
            width={size}
            height={size}
            color="#F9D71C"
          />
          <StarEmptyIcon 
            width={size}
            height={size}
            color="#F9D71C"
          />
          <StarEmptyIcon 
            width={size}
            height={size}
            color="#F9D71C"
          />
        </>
      }
      {
        (rating == 3)
        &&
        <>
          <StarFillIcon 
            width={size}
            height={size}
            color="#F9D71C"
          />
          <StarFillIcon 
            width={size}
            height={size}
            color="#F9D71C"
          />
          <StarFillIcon 
            width={size}
            height={size}
            color="#F9D71C"
          />
          <StarEmptyIcon 
            width={size}
            height={size}
            color="#F9D71C"
          />
          <StarEmptyIcon 
            width={size}
            height={size}
            color="#F9D71C"
          />
        </>
      }
      {
        (rating < 4 && rating > 3)
        &&
        <>
          <StarFillIcon 
            width={size}
            height={size}
            color="#F9D71C"
          />
          <StarFillIcon 
            width={size}
            height={size}
            color="#F9D71C"
          />
          <StarFillIcon 
            width={size}
            height={size}
            color="#F9D71C"
          />
          <StarHalfIcon 
            width={size}
            height={size}
            color="#F9D71C"
          />
          <StarEmptyIcon 
            width={size}
            height={size}
            color="#F9D71C"
          />
        </>
      }
      {
        (rating == 4)
        &&
        <>
          <StarFillIcon 
            width={size}
            height={size}
            color="#F9D71C"
          />
          <StarFillIcon 
            width={size}
            height={size}
            color="#F9D71C"
          />
          <StarFillIcon 
            width={size}
            height={size}
            color="#F9D71C"
          />
          <StarFillIcon 
            width={size}
            height={size}
            color="#F9D71C"
          />
          <StarEmptyIcon 
            width={size}
            height={size}
            color="#F9D71C"
          />
        </>
      }
      {
        (rating < 5 && rating > 4)
        &&
        <>
          <StarFillIcon 
            width={size}
            height={size}
            color="#F9D71C"
          />
          <StarFillIcon 
            width={size}
            height={size}
            color="#F9D71C"
          />
          <StarFillIcon 
            width={size}
            height={size}
            color="#F9D71C"
          />
          <StarFillIcon 
            width={size}
            height={size}
            color="#F9D71C"
          />
          <StarHalfIcon 
            width={size}
            height={size}
            color="#F9D71C"
          />
        </>
      }
      {
        (rating == 5)
        &&
        <>
          <StarFillIcon 
            width={size}
            height={size}
            color="#F9D71C"
          />
          <StarFillIcon 
            width={size}
            height={size}
            color="#F9D71C"
          />
          <StarFillIcon 
            width={size}
            height={size}
            color="#F9D71C"
          />
          <StarFillIcon 
            width={size}
            height={size}
            color="#F9D71C"
          />
          <StarFillIcon 
            width={size}
            height={size}
            color="#F9D71C"
          />
        </>
      }
    </Div>
  );
};

const Div = styled.div`
  display: flex;
  align-items: center;
  gap: 0.25em;
`;
